apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dwk-gitops-project
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  interval: 1m
  path: ./part4/4_08
  prune: true
  validation: client
  targetNamespace: todo-app